Creates Jobs Search Component
Qwwerty/programeiros-frontend pull request #13
Opened 2022-09-02 19:33 UTC by pedroibribas

Task: Creates Jobs Search Component.

Workflow summary:
- Add colors and variants to tailwind.config.js;
- Create JobsSearchForm and JobsSearchInput;
- Add form to Vagas page.

JobsSearchInput functionalities:
- Dropdown closes when clicking anywhere;
- There are two selectors. One is the `select` input (hidden), and the other a `div` as custom selector (rendered). When the user picks an option from the custom selector, `select` changes its value.

Screenshot:
![image](https://user-images.githubusercontent.com/88813381/188222856-69df3260-7ce1-46a2-886e-6d8fdc29ecc0.png)

2022-09-02 20:25 UTC, Alex-dll commented on src/components/JobsSearchInput/index.tsx
> +  };
Acredito que aqui seria melhor escrito se fosse dessa forma, claro teria que ver no quesito render do React.

```suggestion
 const changeHandle = (event: ChangeEvent<HTMLInputElement>) => {
    setInputData(event.target.value);
    setUserAction(event.target.value  === '' ? false : true)
  };
```

2022-09-03 17:19 UTC, pedroibribas commented on src/components/JobsSearchInput/index.tsx
> +  };
Obrigado pela sugestão, @Alex-dll . Eu fiz a alteração. Vou resolver a conversa.

2022-09-03 17:27 UTC, programeiro submitted a review, later dismissed

2022-09-03 17:28 UTC, Alex-dll requested changes

2022-09-03 17:28 UTC, alexdlli commented on src/pages/vagas/index.tsx
>  import { GoTo } from '../../components';
So notei agora, mas se puder remover essa linha de importação para junto da que ja esta importando os componentes

```suggestion
import { Footer, Header, JobsCard, JobsSearchForm, GoTo } from '../../components';
import Image from 'next/image';
```

2022-09-03 17:28 UTC, Alex-dll commented on src/components/JobsSearchInput/index.tsx
> +const JobsSearchInput = ({ type, label, options, placeholder }: JobsSearchInput) => {
Seria importante colocar um I antes do nome pra quando formos declarar algo não chamar a interface e sim o componente.
```suggestion
const JobsSearchInput = ({ type, label, options, placeholder }: IJobsSearchInput) => {
```

2022-09-03 18:38 UTC, programeiro approved these changes

2022-09-03 18:39 UTC, Alex-dll approved these changes

2022-09-03 18:39 UTC, merged